version: "3"

services:
  oa:
    build:
      context: ./
      dockerfile: oa.Dockerfile
    networks:
      - cranky-network
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "8091:8091"
    restart: always
    command: [ "java","-jar","/opt/server/oa.jar","--spring.profiles.active=docker" ]
  fs:
    build:
      context: ./
      dockerfile: fs.Dockerfile
    networks:
      - cranky-network
    environment:
      TZ: "Asia/Shanghai"
    ports:
      - "8090:8090"
    restart: always
    command: [ "java","-jar","/opt/server/fs.jar","--spring.profiles.active=docker" ]

networks:
  cranky-network:
    external: true