apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: monitor-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: monitor
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: monitor_value
        target:
          type: AverageValue
          averageValue: 50
