apiVersion: v1
kind: Service
metadata:
  name: monitor-service
  labels:
    app: monitor
spec:
  type: LoadBalancer
  ports:
    - name: http-metrics
      port: 18082
      targetPort: 18082
  selector:
    app: monitor