apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: monitor-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: External
      external:
        metric:
          name: monitor_value
          selector:
            matchLabels:
              app: monitor
        target:
          type: AverageValue
          averageValue: 50
