apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server-container
          image: 10.13.14.230:5000/server:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 18083