apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: my-server-monitor
  labels:
    team: backend
spec:
  selector:
    matchLabels:
      app: server
  endpoints:
    - port: http-metrics
      path: /actuator/prometheus
