apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: monitor-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: server
  minReplicas: 1
  maxReplicas: 10
  metrics:
    - type: Pods
      pods:
        metric:
          name: request_count
        target:
          type: AverageValue
          averageValue: 10
